### PR TITLE
Release version 2.0.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release version 2.0.2
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Just tested today by @paulnoelcholot, no other change.

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@hibatallahAouadni I got important approval required 👍

**Review by matks — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I tested your PR and it's good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @Hlavtox and @paulnoelcholot !

**Pull request merged**
